### ISSUE TITLE
how to demo text-to-image

### ISSUE THREAD

**Issue by youngwanLEE** [baofff/U-ViT#1]
Hi, I'm very impressed by your excellent work and code.

Could you provide how to demo the trained text-to-image model as you did ImageNet-demo in [colab](https://colab.research.google.com/github/baofff/U-ViT/blob/main/UViT_ImageNet_demo.ipynb)?

Many thanks :)

**Comment by baofff** [comment]
We provide a script `sample_t2i_discrete.py`. You can use this by `python sample_t2i_discrete.py --config=configs/mscoco_uvit_small.py --config.nnet.depth=16 --nnet_path=mscoco_uvit_small_deep.pth --input_path=prompts.txt --output_path=the_directory_to_put_generated_samples`

**Comment by youngwanLEE** [comment]
@baofff Thanks :)
