### ISSUE TITLE
reproducing issue

### ISSUE THREAD

**Issue by youngwanLEE** [baofff/U-ViT#14]
Hi, Thanks for your nice code.

When I tried to reproduce your model(ImageNet256_uvit_L/2), I got a lower value(9.3) than yours (3.40).

I used the command line you recommended and trained using an 8 GPUs environment. 

```
# ImageNet 256x256 (U-ViT-L/2)
accelerate launch --multi_gpu --num_processes 8 --mixed_precision fp16 train_ldm.py --config=configs/imagenet256_uvit_large.py
```

I got this result:

> fid10000 12.06779
> fid50000 9.31433
> loss 0.12881
> lr 0.0002

I compared your config file with the paper and found that `p_uncond=0.15` is different from that(0.1) of your paper.

Could you check this?

Thanks

**Comment by nieshenx** [comment]
Thanks for using our code！
I guess this result is what you see from the eval.log file in the workdir directory. In fact, the fid shown in eval.log is the conditional generation result without classfier-free guidance technology. If you want to get the fid result shown in paper (using classfier-free guidance), you can use the eval_ldm.py file.

**Comment by youngwanLEE** [comment]
@NieShenRuc 

I got `FID 3.52` by following your comment.

Thanks!!

**Comment by eslambakr** [comment]
Dear @youngwanLEE and @NieShenRuc 

To reproduce the results, how many epochs u have trained?

From my understanding based on the readme it is trained for 500k iterations, based on my calculation it means almost 500 epochs., is that correct?

Also, for COCO based on the same calculation it means 2500 epochs, but I guess the number is huge so am I calculating it wrong :D 

Thanks in advance!

**Comment by liangbingzhao** [comment]
Dear @NieShenRuc 
what if the fid in `eval.log` is lower than the fid sampled with `eval_ldm.py` ? what might cause this?
