### ISSUE TITLE
fail to run scripts/extract_test_prompt_feature.py 

### ISSUE THREAD

**Issue by liangbingzhao** [baofff/U-ViT#19]
line 41 `np.save(os.path.join(save_dir, f'{i}.npy'), (prompts[i], c))`, error:
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

it seems that numpy cannot save something like this.

**Comment by SeanNobel** [comment]
I had to modify that part to something like
```python
np.savez(os.path.join(save_dir, str(i)), prompt=prompts[i], context=c)
```

And the reading part in `datasets.py` to
```python
_data = np.load(os.path.join(path, 'run_vis', f), allow_pickle=True)
prompt, context = _data['prompt'], _data['context']
```

**Comment by liangbingzhao** [comment]
same, i solve it just like yours
