### ISSUE TITLE
eval model select

### ISSUE THREAD

**Issue by liangbingzhao** [baofff/U-ViT#20]
when eval, I used to use the `nnet.pth` to sample, which turns out the results are much worse than eval.log. then I compare the code and find in `train_ldm.py` u use the ema model to eval. and I turned to use the ema model to eval, and the results are great. So when eval, choose `nnet.pth` or `nnet_ema.pth`?

**Comment by nieshenx** [comment]
For diffusion models, such as DDPM, the use of EMA usually yields better results, and this is also true for U-ViT. The FID scores reported in the paper were also obtained using the EMA model for evaluation.

**Comment by liangbingzhao** [comment]
thx for the reply. i just not know the gap between ema and non-ema could be so huge. FID could be respectively 7 and 17, using `nnet_ema` and `nnet`.
