### ISSUE TITLE
error whlie using "x0_pred"

### ISSUE THREAD

**Issue by dedekinds** [baofff/U-ViT#3]
If I set "config.pred = 'noise_pred'" as "config.pred = 'x0_pred'" in [cifar10_uvit_small.py](https://github.com/baofff/U-ViT/blob/main/configs/cifar10_uvit_small.py)

![图片](https://user-images.githubusercontent.com/26075974/224229140-982a2ede-d255-4b5a-b9d8-387db8ce576b.png)

How can I fix this error, thanks!

**Comment by baofff** [comment]
Can you print the shape of `xt` and `t`?

**Comment by dedekinds** [comment]
Yes, sure.
![图片](https://user-images.githubusercontent.com/26075974/224547725-f5fcc119-6527-4334-ace3-d0be2e4c90a3.png)

            # self.sde.snr(t).sqrt() torch.Size([500])
            # pred torch.Size([500, 3, 32, 32])
            # self.sde.cum_beta(t).rsqrt() torch.Size([500])
            # x_t torch.Size([500, 3, 32, 32])
            # t shape torch.Size([500])

> Can you print the shape of `xt` and `t`?

**Comment by baofff** [comment]
I get. It is because PyTorch will multiply `t` to the first axis of `xt`, and their dimension 500 and 32 do not match. I have fixed this bug. Thanks.

**Comment by dedekinds** [comment]
> I get. It is because PyTorch will multiply `t` to the first axis of `xt`, and their dimension 500 and 32 do not match. I have fixed this bug. Thanks.

Great job! Thank you!
